hmcts/idam-java-client

- src/test/resources/logback.xml
Otherwise I was getting lots of debug logs when running the tests
> Add logging config

- .travis.yml
https://tools.hmcts.net/jira/browse/RPE-714
Publish client to bintray
```
[ ] Yes
[ ] No
```
> Publish client

- build.gradle
- config/checkstyle/checkstyle.xml
- config/checkstyle/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/idam/client/CoreFeignConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamApi.java
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamClient.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/AuthenticateUserRequest.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/ExchangeCodeRequest.java
- src/test/java/uk/gov/hmcts/reform/idam/client/IdamClientTest.java
- src/test/resources/mappings/oauth2_authorize-successful.json
- src/test/resources/mappings/oauth2_authorize-unsuccessful.json
- src/test/resources/mappings/oauth2_token-successful.json
-  This PR is just an enabler to integrate with Sidam. It adds a request body so that MS IIS accepts the request.
- Setting the Content-Length to 0 doesn't help as it will be removed by Spring Cloud Feign Client implementation.
```
[ ] Yes
[x ] No
```
> Added body to idam requests as it is needed by MS IIS server

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamTestApi.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/test/CreateUserRequest.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/test/UserGroup.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/test/UserRole.java
https://tools.hmcts.net/jira/browse/RPE-1005
Add test api to make integration / functional testing easier and prevent having to duplicate code all over the place
```
[ ] Yes
[ ] No
```
> RPE-1005 Add IdamTestApi

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/client/models/User.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/UserDetails.java
Useful for tests and passing around caseworker details
> Add builder and user object

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/client/CoreFeignConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/UserDetails.java
- src/test/java/uk/gov/hmcts/reform/idam/client/IdamClientTest.java
[Update IDAM client](https://tools.hmcts.net/jira/browse/DIV-5992)
Based on feedback in which a breaking change was inadvertently introduced: 
fixes https://github.com/hmcts/idam-java-client/issues/40
This PR fixes that issue to ensure the API works as expected and that WireMocks still work (de/serialization of JSON is fine)
```
[ ] Yes
[x] No
```
> DIV-5992 Fix UserDetails JSON model

- src/main/java/uk/gov/hmcts/reform/idam/client/IdamApi.java
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamClient.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/TokenRequest.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/TokenResponse.java
- src/test/java/uk/gov/hmcts/reform/idam/client/IdamClientTest.java
https://tools.hmcts.net/jira/browse/BPS-1120
add getting openid token
```
[ ] Yes
[x] No
```
> add openid token

- src/main/java/uk/gov/hmcts/reform/idam/client/models/ExchangeCodeRequest.java
- src/test/java/uk/gov/hmcts/reform/idam/client/IdamClientTest.java
fix property names form data, verify request body in tests
```
[ ] Yes
[x] No
```
> fix property names form data, verify request body

- src/main/java/uk/gov/hmcts/reform/idam/client/IdamApi.java
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamClient.java
deprecate oauth2/authorize
and will release 1.4.0
```
[ ] Yes
[x] No
```
> deprecate oauth2/authorize

- src/main/java/uk/gov/hmcts/reform/idam/client/IdamClient.java
- src/test/java/uk/gov/hmcts/reform/idam/client/IdamClientTest.java
https://tools.hmcts.net/jira/browse/BPS-1120
change openid scope
```
[ ] Yes
[x] No
```
> change openid scope

- src/main/java/uk/gov/hmcts/reform/idam/client/IdamApi.java
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamClient.java
- src/test/java/uk/gov/hmcts/reform/idam/client/IdamClientTest.java
https://tools.hmcts.net/jira/browse/ACA-14
getUserByUserId API
```
[ ] Yes
[ ] No
```
> getUserByUserId API

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/idam/client/CoreFeignConfiguration.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/SSCS-7729
```
[ ] Yes
[ ] No
```
> SSCS-7729 Add configurable client logging

- src/contractTest/java/uk/gov/hmcts/reform/idam/client/IdamClientConsumerTest.java
- src/contractTest/resources/application.yml
- src/main/java/uk/gov/hmcts/reform/idam/client/IdamClient.java
- src/main/java/uk/gov/hmcts/reform/idam/client/OAuth2Configuration.java
Making clientScope as a configurable property
```
[ ] Yes
[x ] No
```
> Making clientScope as a configurable property like redirect-uri

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/idam/client/IdamClientConsumerTest.java
- src/main/java/uk/gov/hmcts/reform/idam/client/models/UserInfo.java
https://tools.hmcts.net/jira/browse/BPS-1256
Adds new /o/userinfo pac 
```
[ ] Yes
[X] No
```
> impr: BPS-1256 add new /o/userinfo pact test

- .github/workflows/gradle.yml
- build.gradle
This changes the source compatibility to Java 11 and updates the relevant dependencies
> Upgrade to Java 11

- jitpack.yml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> DTSPO-1792 - set java version for jitpack

- .github/workflows/gradle.yml
- .github/workflows/jitpack_build.yml
- jitpack.yml
- remove bintray upload 
- create workflow to force jitpack to build on tag push
```
[ ] Yes
[ ] No
```
> DTSPO-1792 jitpack build

- src/main/java/uk/gov/hmcts/reform/idam/client/CoreFeignConfiguration.java
Invoke ApacheHttpClient as Conditonal
```
[ ] Yes
[X] No
```
> Marking Apachehttpclient as conditional

- build.gradle
> Fix artifact name while publishing

- build.gradle
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Update owasp dependencyCheck plugin

- build.gradle
Add consumer version to fix pacts
```
[ ] Yes
[x] No
```
> Add consumer version
